### PR TITLE
Add check for ADR file names

### PR DESCRIPTION
**Pull request by giorgiosironi**
Very simple example of what Github Actions for CI look like in comparison to Travis CI.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Building in https://github.com/libero/community/commit/8522c2db889927abb27c4b35f806fd5ce9257faf/checks?check_suite_id=265713666

/cc @joelsummerfield we are enabled to use Github Actions in the Libero organization.

**Review by erezmus — APPROVED** [review]

**Comment by giorgiosironi** [comment]
Do you approve the use of the Github actions or the file name check?

**Comment by erezmus** [comment]
> Do you approve the use of the Github actions or the file name check?

filename check. though now that i looked at the link, its failing?

**Comment by giorgiosironi** [comment]
The [output I see](https://github.com/libero/community/pull/28/checks?check_run_id=260863198) is:
```
 Check ADRs naming convention
0s
0004-align-technology-practice-process.md
Run set -e
  set -e
  cd doc/adr/
  for file in *; do echo $file; [[ $file =~ ^.+\.md$ ]]; done
  shell: /bin/bash -e {0}
0001-record-architecture-decisions.md
0002-continuously-delivery-travis-ci.md
0003-publisher-not-using-react.md
0004-align-technology-practice-process.md
```

**Comment by giorgiosironi** [comment]
Demonstration superseded by https://github.com/libero/article-store/pull/74/

**Pull request closed without merging**
